version: '3.5'

services:
  websocket:
    image: 4programmers/websocket:latest
    networks:
      - coyote
    tty: true
    environment:
      PORT: "8888"
      REDIS_HOST: "redis"
      APP_KEY: ""
    ports:
      - 8888:8888

networks:
  coyote:
    name: coyote